### ISSUE TITLE
[Refactor] Rename Category to Group

### ISSUE THREAD

**Issue by vincentrohde** [vincentrohde/harvest-dashboard#47]
### IS State:
Across the project there are a lot of files, that refer to "_Categories_" (name if something could be either a projects or a tasks). An example would be the `./client/src/types/Categories.ts` file.

### SHOULD State:
Whenever you find a reference to "categories" / "category" this should be renamed to "groups" / "group".

### Example

**Before**

`./client/src/types/Categories.ts`
```
export type categoriesType = CategoryInterface[];

export interface CategoryInterface {
    id: number;
    name: string;
}
```

**After**

`./client/src/types/Groups.ts`
```
export type groupsType = GroupsInterface[];

export interface GroupInterface {
    id: number;
    name: string;
}
```

When you have updated the naming, please make sure to update the imports and references to the new name as well.
So if you renamed for example a function, make sure that wherever the function was used, the name is updated.

When everything is updated, please make sure, that nothing broke during renaming 👍

**Comment by Himanshu664** [comment]
I am working on it

**Comment by LucasRobs** [comment]
hi @vincentrohde i would like to solve this problem, could you assign me?

**Comment by vincentrohde** [comment]
@LucasRobs I just assigned it to you now. If you have any issues with starting the project, or questions about how things (should) work, feel free to ping me 👍

**Comment by LucasRobs** [comment]
@vincentrohde  That's it, I'm still learning to create PRs and I couldn't put you as reviewers. thanks for understanding
