### ISSUE TITLE
[Feature] Sticky Header for the Frontend

### ISSUE THREAD

**Issue by vincentrohde** [vincentrohde/harvest-dashboard#48]
### IS State:

Currently the title is just above the DatePicker.

![page-title-currently](https://user-images.githubusercontent.com/25182140/131998401-4f978645-96c9-4cf5-983e-a4d1da46b335.png)

### SHOULD State:

It would be great, if the title is part of a sticky colorful header. This would improve the UI. The header doesn't have to be extra fancy. Something minimal like this would work well:

![page-header](https://user-images.githubusercontent.com/25182140/131998032-0c0b19e8-b146-4353-a71e-4b646a788e14.png)

### How To Reproduce

Start the project and see if there's a Header with title, instead of the title just floating around 😉

**Comment by davidackroyd99** [comment]
I can do this! have forked, will submit a pr soon

**Comment by davidackroyd99** [comment]
Not a react pro, and finding it very difficult to follow the build instructions. Do you making it a bit clearer? Run npm install on the client but it just errors :(

**Comment by vincentrohde** [comment]
@davidackroyd99 I have updated the README.md for the project. You're right the documentation is not the best at the moment. I've seen that you forked the repo. On your local you will need to run `npm install` in both the `./client` and the `./server` directory.

Could you maybe post the error you get when running `npm install` in `./client`?

### If installation works

Once both are installed you will need to run `npm run start` first in the `./server` directory. Once the server is up, you should run `npm run start` in the `./client` directory. The client (webpack-dev-server) will throw errors if it cannot reach the Node server.

I am not sure if you will need a [Harvest account](https://www.getharvest.com) for this issue. The feature should be doable without it imo. If it breaks without the account, you would need a [free version Harvest account](https://support.getharvest.com/hc/en-us/articles/360048685631-Is-there-a-free-version-of-Harvest). It's free for personal use :) But I think the client will only throw some errors in the console, if no account is given.

**Comment by vincentrohde** [comment]
@davidackroyd99 any updates?

**Comment by davidackroyd99** [comment]
> @davidackroyd99 any updates?

Thanks for this, I shall try now and give an update

**Comment by ali1059** [comment]
Hey,

Do you still need help with this navbar issue ? I am available to contribute

**Comment by vincentrohde** [comment]
@davidackroyd99 Did you already work on this issue? If not, I would assign it to @ali1059 , if that's okay with you 👍

**Comment by vincentrohde** [comment]
@ali1059 I will assign this ticket now to you, you can start working on it 👍

**Comment by ali1059** [comment]
I have forked the repo and will submit a pr soon

**Comment by vincentrohde** [comment]
if you have any questions, or issues with bringing up the project feel free to ping me

**Comment by ali1059** [comment]
![navbar](https://user-images.githubusercontent.com/36314122/135644643-588992d2-7cfa-443a-a4db-179919510036.png)

Hey Vincent,

Is it ok like this or should I move the text to the center?

**Comment by vincentrohde** [comment]
@ali1059 could you remove the `TEST` in the title. I am not sure about the centering, just open a Pull Request and I will try it out myself 👍

**Comment by ali1059** [comment]
@vincentrohde I have removed the test text I was using it to test if local changes are working and I have created a PR and kindly let me know if theres need of any changes

**Comment by vincentrohde** [comment]
@ali1059 I just merged your pull request. Thank you very much for your help 💯
