### ISSUE TITLE
[Feature] Setup Prettier

### ISSUE THREAD

**Issue by vincentrohde** [vincentrohde/harvest-dashboard#57]
To promote a standard code format, it would be great if the project makes use of Prettier (https://prettier.io/).

**Acceptance Criteria**

- [ ] Prettier is installed in the project's root `./package.json`

- [ ] A configuration is set up in the project's root directory, with the following values:

```
printWidth: 100
tabWidth: 4
singleQuote: true
bracketSpacing: false
endOfLine: 'auto'
trailingComma: 'all'
```

- [ ] Formatting script is implemented in the project's root `./package.json`

```
"scripts": {
    "format-code": "..."
}
```

**Comment by selamanse** [comment]
Hi @vincentrohde I'd really like to try this
